http.host: 0.0.0.0
pipeline.batch.size: 125
pipeline.workers: 16
xpack.monitoring.elasticsearch.hosts: http://es01:9200
xpack.monitoring.elasticsearch.password: ${ELASTIC_PASSWORD}
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.enabled: true
