- pipeline.id: sufragantes
  path.config: "/usr/share/logstash/pipeline/sufragantesdep.conf"

- pipeline.id: jurados
  path.config: "/usr/share/logstash/pipeline/juradosdep.conf"

- pipeline.id: personas
  path.config: "/usr/share/logstash/pipeline/lab_personas.conf"